### ISSUE TITLE
Is a periodic task really needed to clear the history?

### ISSUE THREAD

**Issue by Hornwitser** [soyuka/pidusage#105]
pidusage sets an interval function on the event loop which requires that it be manually cleared in order to gracefully exit node when using this library.  But why is this necessary?  You only observe the result of the invalidator task when the `get()` function of the history lib is invoked,so you might as well do the invalidation when `get()` is invoked.

At the very least call `unref()` the invalidation interval so it doesn't keep the event loop alive.

**Comment by soyuka** [comment]
This commit explains it (see description: https://github.com/soyuka/pidusage/commit/4789ae9564ccfbf2fd638cac467a254ec931d875#diff-88c126b24fe4510cfe06437cb9045a0e). TLDR: It's necessary to obtain a precise "usage" over time where you need to compute values over time to obtain a result close to what `ps` does on unix-based systems. 

If you see something that can be improved by having the same results I'd be glad to review/consider it.

**Comment by Hornwitser** [comment]
What I was thinking of was to remove the interval and run the invalidate task on set and get.  Though that caused the issue of performance slowdown when there's lots of monitoring going on at the same time, which I think could be solved by not running the invalidate task as often.

The alternative would be to unref the interval and not think about it too much.  I'll post two pull requests detailing the two approaches.

**Comment by soyuka** [comment]
Thanks for fixing this (#107)
