### ISSUE TITLE
Node process doesn't exit if I use pidusage

### ISSUE THREAD

**Issue by StoneT2000** [soyuka/pidusage#108]
I tried running `node test.js` which contains the following code:

```js
var pidusage = require('pidusage')
pidusage(process.pid).then((s) => {
  console.log(s);
});
```

However, it never exits and just hangs there for a long time. Is something wrong?

**Comment by codexuexi** [comment]
https://github.com/soyuka/pidusage/issues/91
？？？
You need a good habit
