### ISSUE TITLE
There is no interval.unref in Electron

### ISSUE THREAD

**Issue by lierdakil** [soyuka/pidusage#109]
https://github.com/soyuka/pidusage/blob/b52a86c219552fb66613e524b9900646f50cdc0a/lib/history.js#L42

This line breaks compatibility with Electron apps, which uses Chromium-provided `setTimeout`/`setInterval` instead of Node's implementations.

Perhaps a reasonable band-aid is to check if `unref` function exists before invoking it?

**Comment by simonepri** [comment]
@lierdakil Would you mind submitting a PR?
