### ISSUE TITLE
Negative elapsed value

### ISSUE THREAD

**Issue by mahmoud34abc** [soyuka/pidusage#118]
For some reason, the "elapsed" value is negative for me.
I put the elapsed value in a discord embed message. I tried to divide it by 1000 at first, so I could get seconds, but its just negative. I thought about just leaving it alone, but to no avail.
```js
client.on("message", message => {
  if (message.content == "m!stats") {
    pidusage(process.pid, function (err, stats) {
      const embed = new Discord.MessageEmbed()
        .setTitle("Mahie Status")
        .setAuthor(client.user.username, client.user.avatarURL())
        .setColor(0xff0066)
        .setDescription("You can read all information about Mahie here!")
        .setFooter("Made with <3 by Mahmoud! - Version " + process.env.VERSION)
        //.setImage("")
        //.setThumbnail("")
        .setTimestamp()
        //.setURL()
        .addFields(
          {name: "CPU", value: stats.cpu + "%", inline: true},
          {name: "Memory", value: `${stats.memory / 1024 / 1024}` + " MB", inline: true},
          {name: "Time Elapsed", value: `${stats.elapsed}` + " ms", inline: true}, // stats.elapsed HERE
          {name: "Language", value: "discord.js 12.3.1", inline: true},
          {name: "Hosted on", value: "glitch.com", inline: true},
        )
      message.channel.send({embed});
    })
  }
});
```

It comes out as the following:
![image](https://user-images.githubusercontent.com/70000093/94755330-810ba800-0394-11eb-9185-f8c6d4ffc449.png)
If there is anything I'm doing wrong, please tell

**Comment by soyuka** [comment]
Hi,

Give me more informations about the operation system you're using.

**Comment by soyuka** [comment]
Did you try using `process.cpuUsage`, `process.memoryUsage`?

**Comment by mahmoud34abc** [comment]
I'm using pidusage to get the usage of CPU and Memory. (`stats.cpu` for cpu and `stats.memory` for memory. The only thing that does not work, is the time elapsed since the process is open. (`stats.elapsed`). You can see in the code:

```js
    pidusage(process.pid, function (err, stats) {
      const embed = new Discord.MessageEmbed()
        (...)
        .addFields(
          {name: "CPU", value: stats.cpu + "%", inline: true},
          {name: "Memory", value: `${stats.memory / 1024 / 1024}` + " MB", inline: true},
          {name: "Time Elapsed", value: `${stats.elapsed}` + " ms", inline: true}, // The problem is here
          {name: "Language", value: "discord.js 12.3.1", inline: true},
          {name: "Hosted on", value: "glitch.com", inline: true},
        )
      message.channel.send({embed});
    })
  }
});
```

And as you can see in the screenshot, it gives out a negative value.

**Comment by soyuka** [comment]
Can you try using `pidusage(process.pid, {usePs: true}, function (err, stats) {})` ?

**Comment by mahmoud34abc** [comment]
Yeah, I tried that now. It types out a 0 ms. I'll see if it changes after some time since restart.
![image](https://user-images.githubusercontent.com/70000093/96049872-f38e8480-0e78-11eb-858c-dcdab442a767.png)
```js
client.on("message", message => {
  if (message.content == "m!stats") {
    pidusage(process.pid, {usePs: true}, function (err, stats) {
      const embed = new Discord.MessageEmbed()
       (...)
        .addFields(
          (...)
          {name: "Time elapsed since restart", value: `${stats.elapsed}` + " ms", inline: true},
        )
      console.log(stats)
      message.channel.send({embed});
    })
  }
});
```
This is the log
> {
>   cpu: 0,
>   memory: 48918528,
>   ppid: 1557,
>   pid: 1558,
>   ctime: 0,
>   elapsed: 0,
>   timestamp: 1602712598404
> }

**Comment by soyuka** [comment]
From the look of it, I'd say that the distribution you're using has a format that we may not support. Using `ps` we documented everything in https://github.com/soyuka/pidusage/blob/master/lib/ps.js#L57-L85. 

I'd suggest that you use the [`process.uptime()`](https://nodejs.org/api/process.html#process_process_uptime) value instead as it looks that this is what you're looking for. I'd like to fix the issue but if you do not have access to the underlying system this will not be possible.

**Comment by mahmoud34abc** [comment]
Yeah, I don't think I really have access to the system lmao. `process.uptime()` works greatly, so huge thanks for that! I guess I'll close the issue since I do not have access to the underlying system lol.

Anyways here is the line if someone needs to use it!
```js
client.on("message", message => {
  if (message.content == "m!stats") {
    pidusage(process.pid, {usePs: true}, function (err, stats) {
      const embed = new Discord.MessageEmbed()
        (...)
        .addFields(
          (...)
          {name: ":clock: Time elapsed since restart", value: `${Math.round(process.uptime() / 60)}` + " minute(s)", inline: true},
        )
      message.channel.send({embed});
    })
  }
});
```
![image](https://user-images.githubusercontent.com/70000093/97093752-0b22f580-164f-11eb-9f5b-c19f83495aad.png)
