### ISSUE TITLE
OpenBSD - PM2

### ISSUE THREAD

**Issue by Kingsy** [soyuka/pidusage#120]
I am using PM2 and I am getting the following in my logs.

PM2      | Error caught while calling pidusage
PM2      | Error: openbsd is not supported yet, please open an issue (https://github.com/soyuka/pidusage)
PM2      |     at get (/usr/local/lib/node_modules/pm2/node_modules/pidusage/lib/stats.js:54:21)
PM2      |     at pidusage (/usr/local/lib/node_modules/pm2/node_modules/pidusage/index.js:25:5)
PM2      |     at Object.getMonitorData (/usr/local/lib/node_modules/pm2/lib/God/ActionMethods.js:60:5)
PM2      |     at tasks (/usr/local/lib/node_modules/pm2/lib/Worker.js:149:9)
PM2      |     at Domain.<anonymous> (/usr/local/lib/node_modules/pm2/lib/Worker.js:192:7)
PM2      |     at Domain.run (domain.js:370:14)
PM2      |     at Timeout.wrappedTasks [as _onTimeout] (/usr/local/lib/node_modules/pm2/lib/Worker.js:191:7)
PM2      |     at listOnTimeout (internal/timers.js:549:17)
PM2      |     at processTimers (internal/timers.js:492:7)

The service seems to be responding and working perfectly apart from this.

Could you please advise?

Thanks

**Comment by soyuka** [comment]
Oh sorry I missed this issue. Sure thing, does openbsd use procfiles ? Is `ps` available ? Can you run a few tests for me ?

**Comment by Kingsy** [comment]
Hi, looks like I missed your response too. hah. sorry about that.

Yes, ps is available

ps
  PID TT  STAT        TIME COMMAND
80129 p0  Sp       0:00.03 -ksh (ksh)
12520 p0  R+pU/0   0:00.01 ps

I am not sure what you mean by procfiles. I can absolutely run some tests for you. let me know.

**Comment by soyuka** [comment]
https://github.com/soyuka/pidusage/blob/master/lib/stats.js#L15 

Just add:

```
openbsd: 'ps'
```

and run `npm i && npm test` and let me know if it works :D

**Comment by essays-on-esotericism** [comment]
@soyuka I can confirm this works - I've opened up a pull request here: https://github.com/soyuka/pidusage/pull/155
