### ISSUE TITLE
Does wmic is required on windows?

### ISSUE THREAD

**Issue by LeonardoRick** [soyuka/pidusage#124]
I'm currently trying to run on a windows machine and get the error `spawn wmic ENOENT`.

Is that mandatory?

**Comment by soyuka** [comment]
yes unless you know another way of having these stats on windows? also it should be installed in almost every windows OS what is yours?

**Comment by LeonardoRick** [comment]
it's windows 10. I'm trying to run this library on several different win 10 machines and sometimes the environtment path is not properly setup. I guess my solution is to keep having this dependecy to update variables to properly match the executable.

In case it's not installed, whats the trustable way to install wmic?

**Comment by soyuka** [comment]
I don't  think there's a way to install it as it should be present on your windows (it's used by the task manager IIRC) maybe an administrator issue?

**Comment by hirios** [comment]
> I'm currently trying to run on a windows machine and get the error `spawn wmic ENOENT`.
> 
> Is that mandatory?

Find out if Windows is modified? for example, those lite versions of Windows

**Comment by liuqian1996** [comment]
wmic seems removed on windows 11
