### ISSUE TITLE
PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value 

### ISSUE THREAD

**Issue by azoz-w** [soyuka/pidusage#171]
**API Platform version(s) affected**: keymetrics/pm2:16-alpine

**Description**  
I am running PM2 to have a nuxt and nestjs project on a single process. after a few days of running fine and with no apparent reason, everything stops and I get the error 
```
PM2 warn: [pidusage] We couldn't find uptime from /proc/uptime, using os.uptime() value 
```

**How to reproduce**  
I have no clear idea how to reproduce it

I would appreciate some help with the issue

**Comment by soyuka** [comment]
Hi, you can silent the error using `PIDUSAGE_SILENT=1`. See also https://github.com/Unitech/pm2/issues/4890
