### ISSUE TITLE
Python extension error in VS code

### ISSUE THREAD

**Issue by JulenXabierCano** [soyuka/pidusage#178]
Im trying to use the python extension on VScode and i get this error:

[Extension Host] Python Extension: (pidusage) Error: 
Mon Apr 29 2024 21:37:26 GMT+0200 (Central European Summer Time) Wmic errored, please open an issue on https://github.com/soyuka/pidusage with this message.
Command was "wmic PROCESS 28568 get workingsetsize,usermodetime,kernelmodetime" 
 System informations: 
 - release: 10.0.22631 
 - type Windows_NT 
Wmic reported the following error: No hay instancias disponibles..
Wmic exited with code 0.
Stdout was empty
	at ChildProcess.<anonymous> (c:\Users\julen\.vscode\extensions\geecode.geecode-python-2019.5.10\out\client\extension.js:83:77246)
	at ChildProcess.emit (node:events:517:28)
	at maybeClose (node:internal/child_process:1098:16)
	at ChildProcess._handle.onexit (node:internal/child_process:303:5)
w @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
S @ rpcProtocol.ts:458
Q @ rpcProtocol.ts:443
M @ rpcProtocol.ts:373
L @ rpcProtocol.ts:299
(anonymous) @ rpcProtocol.ts:161
y @ event.ts:1156
fire @ event.ts:1187
fire @ ipc.net.ts:650
q.onmessage @ localProcessExtensionHost.ts:376

**Comment by soyuka** [comment]
The process you try to reach does not exist anymore, I suggest reporting that to the geecode-python extension at https://marketplace.visualstudio.com/items?itemName=geecode.geecode-python
