### ISSUE TITLE
Its not telling accurate ram and CPU usage

### ISSUE THREAD

**Issue by muhammadfaizan** [soyuka/pidusage#18]
I was trying out this on my ubuntu server, the 
`top` command showed me cpu usage of 40%
while pidusage of same process showed 0% cpu usage, can you tell me where i am wrong, and is there a fix?
Also the RAM consumption was above 90MB and it showed 0.63MB

**Comment by soyuka** [comment]
Those numbers don't feel right. Can you give me a way to reproduce this?

**Comment by soyuka** [comment]
Just tested this myself and I got similar results between `ps -o pcpu,rss -p "$pid"` and `pidusage` (on debian, ubuntu would take the same path). Please provide a reproducible pattern.

**Comment by muhammadfaizan** [comment]
yes I used `ps` as well, i am on ubuntu micro instance of _Ec2_.

It is happening in _ubuntu_ only, although it works well with Darwin, locally.

**Comment by soyuka** [comment]
Can you give me a way to reproduce please?

On Darwin this uses `ps` internally so they would not be any differences.

**Comment by muhammadfaizan** [comment]
I am using the following code. this will reproduce the result for you.
```
'use strict';
const exec = require('child_process').exec;
const execSync = require('child_process').execSync;
var pusage = require('pidusage');

const KB = 1024;
const MB = 1024 * KB;
const GB = 1024 * MB;

setInterval(function() {
  pusage.stat(selenium.pid, function(err, stat) {
    if (err) {
      console.log(err);
    }
    console.log(`${selenium.pid} : Pcpu : ${stat.cpu}`);
    console.log(`${selenium.pid} :Mem : ${stat.memory / MB} MB`); 
           
    }
  });
}, 5000);
```

**Comment by soyuka** [comment]
I can't spam phantomjs, how 're you increasing cpu usage? 

I might have an idea though is that `ps` computes child processes.
