### ISSUE TITLE
Why unmonitor is needed? 

### ISSUE THREAD

**Issue by atypicalprogrammer** [soyuka/pidusage#25]
I'd like to know why the unmonitor method is needed?

**Comment by atypicalprogrammer** [comment]
Do we need to call every time after we call stat? Or only 1 time when we want to stop the monitoring?

**Comment by soyuka** [comment]
On windows you don't need it, it is on linux systems ([see here](https://github.com/soyuka/pidusage#linux)) to clear the process usage history stack.
