### ISSUE TITLE
Windows cpu versus task monitor

### ISSUE THREAD

**Issue by atypicalprogrammer** [soyuka/pidusage#26]
In task monitor, it shows as 25% , in piduage it shows as 100%. Why is that? You show per core or something?

**Comment by soyuka** [comment]
I have no idea, on windows we're using [`wmic`](https://github.com/soyuka/pidusage#windows). You might want to try to launch the command by hand to see if something is wrong ([see this line](https://github.com/soyuka/pidusage/blob/master/lib/stats.js#L130)).
