### ISSUE TITLE
CPU data is not accurate in the very beginning of a process

### ISSUE THREAD

**Issue by xiaoshimimi** [soyuka/pidusage#27]
cpu usage output at the beginning of a process:

```
usage: 107.4999999996089
pidusage: 1062.4999999768079

```

**Comment by soyuka** [comment]
Operating system? Thanks.

**Comment by xiaoshimimi** [comment]
Redhat 6

**Comment by soyuka** [comment]
It's running `ps -o pcpu,rss -p some_PID_here`, could you give me a sample output of this command that runs on redhat? Thanks!

**Comment by soyuka** [comment]
Also, please update pidusage to the latest, I might have fixed this.

**Comment by gboysko** [comment]
FWIW, I see a CPU usage of over 100 on CentOS (a value of 158.76288...). Not generally reproducible, though.
