### ISSUE TITLE
Checking usage high CPU% on Windows

### ISSUE THREAD

**Issue by TJKoury** [soyuka/pidusage#32]
The WMHost process spikes when using this library.

**Comment by soyuka** [comment]
Yeah I know, but we have to blame windows for that... Calling wmic will use cpu, more than it should IMO and I tried to find better solutions without success, any suggestions? 

Btw, at what interval do you call the script?

**Comment by TJKoury** [comment]
Sorry about the delay on this comment; I called it about 1 / sec.  There seems to be some sort of compounding effect, as the WMHost stayed pegged at ~90% even after all node processes had exited.

**Comment by soyuka** [comment]
Are you using the latest version ?

**Comment by TJKoury** [comment]
Yes, on Windows 10 x64 bit.

**Comment by TJKoury** [comment]
Node 4.2.2, 6.7, and 7.0

**Comment by soyuka** [comment]
I meant pidusage@1.1.0.

It's really not supposed to take lot of cpu usage. Can you please launch the following command in a `cmd.exe`? 

```
wmic PROCESS SOME_PROCESS_ID_HERE get workingsetsize,usermodetime,kernelmodetime
```

Do you see the same cpu usage? Is there any error ? Thanks!

**Comment by TJKoury** [comment]
Yes, same thing, and after a few thousand iterations I get broken pipes,
etc.

If you (or I) stick in a debounce algorithm that might work.

**Comment by soyuka** [comment]
> stick in a debounce algorithm that might work.

What do you mean by that?

So, if I read correctly, the command `wmic PROCESS SOME_PROCESS_ID_HERE get workingsetsize,usermodetime,kernelmodetime` is using anormal cpu resources. So, it's definitely a windows issue, sad they don't have a github issue tracker lol.

Maybe it's related to this: http://lokna.no/?p=1430 ? 

Some search results :

http://serverfault.com/questions/108829/why-is-my-system-event-log-full-of-wmi-performance-adapter-messages
https://blogs.technet.microsoft.com/askperf/2014/08/12/wmi-how-to-troubleshoot-high-cpu-usage-by-wmi-components/

**Comment by TJKoury** [comment]
Debounce =  limit the number of calls / sec, or wait for the process to
exit before another can be executed, or some mix of both.

**Comment by soyuka** [comment]
Hmm, but this you'd have to implement yourself. I mean, pidusage already give results only [`on close`](https://github.com/soyuka/pidusage/blob/master/lib/stats.js#L141).

For example:

```
let interval = 1000

function bounce() {
setTimeout(function() {
  pidusage.stat(process.pid, function(err, stat) {
    if (err) { console.error(err) }
    //do something with stat
    bounce()
  })
}, 1000)
}
```

Note that instead of using `pidusage` to get a nodejs process usage, you can use [`process.cpuUsage`](https://nodejs.org/api/process.html#process_process_cpuusage_previousvalue) that comes with node 6.1.0+.

**Comment by TJKoury** [comment]
I think I will just stick with process.cpuUsage, and building a debounce
for my own app.

Thanks for being responsive!

**Comment by soyuka** [comment]
Yeah, advantage of this script is to be used for anything that is not nodejs, or for an external pid :).
