### ISSUE TITLE
how can i call the stat function synchronously?

### ISSUE THREAD

**Issue by puneetkapoor18** [soyuka/pidusage#40]
how can i call the stat function synchronously?

**Comment by soyuka** [comment]
There is no synchronous implementation.

**Comment by puneetkapoor18** [comment]
thanks for the information, i also want to confirm that the CPU load for win is coming incorrect .

i get Pcpu: 26859.375 this value for the process but it should be 0 % instead.

i used windows-cpu module and its getting correct value.
Also what is the unit of the CPU load i expect it to be %.

**Comment by soyuka** [comment]
Yeah this sometimes happened. I've try a fix in my last commit.

The unit is `%` but the number will be given as float.

**Comment by puneetkapoor18** [comment]
It's still not working, i am getting Pcpu: 88387039.0625 which is over 100%.

I expect it to be between 0-100.

**Comment by soyuka** [comment]
This is weird, I sadly have no windows to test this. Could you give me more informations?
What is your windows version? Node version? Does the value corrects itself over time? 

Thanks!

**Comment by puneetkapoor18** [comment]
Node version :- v0.10.38
Windows Version :- Win 10 Enterprise it doesn't corrects itself over time.

**Comment by soyuka** [comment]
Wow, node `0.10` is kinda old. We have people using windows 10 enterprise and they didn't report this issue :/.

I'll take a look tonight on a windows device and let you know!

ping @vmarchaud

**Comment by soyuka** [comment]
@puneetkapoor18 didn't forget just no time, on in asap!

**Comment by Pixmap** [comment]
I've tried to use it on Windows 7 x64 with node 6.11.0 but I have the same issue.
stat.cpu returns 398833.71661, but Windows task manager shows 25%
My CPU is Intel i5-4440 and my test program is loading one kernel on 100%.

**Comment by soyuka** [comment]
My guess is that [this value](https://github.com/soyuka/pidusage/blob/master/lib/stats.js#L171) is wrong. I'm having trouble finding the correct documentation about the kernelmodetime and usermodetime unit in windows. 

What's also weird is that on `appveyor`, values appear to be correct!

**Comment by soyuka** [comment]
https://ci.appveyor.com/project/soyuka/pidusage/build/job/32txjp46uhk9597e for example

**Comment by soyuka** [comment]
Please state how you're using the library, I sadly can not reproduce the issue.

**Comment by Pixmap** [comment]
```
var pusage = require('pidusage')
var pid = 5604; // it is Firefox process
pusage.stat(pid, function(err, stat) {
	if(err) {
		console.log(err);
	} else {
		console.log('Cpu: %s', stat.cpu)
		console.log('Mem: %s', stat.memory) //those are bytes
	}
})
// Unmonitor process
pusage.unmonitor(pid);
```

**Comment by soyuka** [comment]
You should not `unmonitor` like this, only when you don't want to stat anymore:

```
var pusage = require('pidusage')
var pid = 5604; // it is Firefox process
var numStat = 0

// stat every second
var interval = setInterval(function() {
  pusage.stat(pid, function(err, stat) {
       numStat++
	if(err) {
		console.log(err);
	} else {
		console.log('Cpu: %s', stat.cpu)
		console.log('Mem: %s', stat.memory) //those are bytes
	}
       //for example stop after 100 calls
       if (numStat > 100) {
           clearInterval(interval)
           pidusage.unmonitor(pid)
       }
  })
}, 1000)
```

I'll change the readme example

**Comment by Pixmap** [comment]
Thanks! Now it give me valid numbers.

**Comment by soyuka** [comment]
:D :heart: Sorry about the misleading informations!
