### ISSUE TITLE
Wrong CPU usage 

### ISSUE THREAD

**Issue by sdellava** [soyuka/pidusage#41]
Hi Devs, I've guess the CPU usage shown in the bottom of the IOTA Windows Wallet is not correct.

It use this module to get data to display.

It is almost the double of the value reported by the System monitor. Memory usage will also display the RSS only.

As you can see in this screenshot the wallet says 70% and the real value is 37%

![image](https://user-images.githubusercontent.com/11772150/28704796-f2a9e866-736c-11e7-885e-33a61d6031a4.png)

Even momory seems not correct

**Comment by soyuka** [comment]
#40

**Comment by soyuka** [comment]
I'm using https://technet.microsoft.com/en-us/library/ee176718.aspx which states:

> For each process in the collection, calculate the total processor use.
- Add the values for KernelModeTime and UserModeTime.
- Together, KernelModeTime and UserModeTime tell you the total amount of processor time allocated to a process. To ensure that these values are added and not concatenated, use the VBScript function CSng to convert the variant data to the single data type.
- Divide the combined value by 10,000,000.
Processor use times are reported in 100-nanosecond increments. (A nanosecond is one-billionth of a second; 100 nanoseconds equal one ten-millionth of a second.) This calculation results in processor use being reported in seconds.

Memory is using the `workingsetsize`.

In your screenshot, you're showing the total cpu usage not the process one no?

**Comment by sdellava** [comment]
It should be the total. I'm a user, not the dev. 

Anyway. Even if it is the process CPU it is wrong.

**Comment by soyuka** [comment]
> It should be the total. I'm a user, not the dev.

I'm sorry I'm not the dev of the IOTA Wallet therefore I can't help you to get the total cpu usage. I'll try to see if someone there has more informations to give me. 

> Anyway. Even if it is the process CPU it is wrong.

Maybe it is, but by saying so you're not helping to resolve the issue.

**Comment by soyuka** [comment]
May you give me the windows version you're currently on? Thanks.

**Comment by soyuka** [comment]
Bad usage in the given software. Fix: https://github.com/iotaledger/wallet/pull/175

**Comment by sdellava** [comment]
here the windows version details:

![image](https://user-images.githubusercontent.com/11772150/28723339-bbe79b94-73b6-11e7-8929-4e72997274d0.png)

**Comment by soyuka** [comment]
Your issue is fixed in my PR of the software project. Thanks anyway!
