### ISSUE TITLE
Calculated CPU usage wrong

### ISSUE THREAD

**Issue by papakai** [soyuka/pidusage#42]
See here: https://github.com/Unitech/pm2/issues/3299

If you need os dependent details, please let me know - at east I know we're using Debian on that server. 
Any questions concerning the technical implementation -> please address them to Unitech.
They just asked me to open an issue here.

**Comment by soyuka** [comment]
I'm not sure I get the issue. The cpu values should be close to what `top` gives you. Also, please be sure that you're monitoring the same processes (with Cluster you'll have more then 1 process per application each having their own cpu value).

**Comment by soyuka** [comment]
The process identified by `13581` has 100% on both jlist and top output so I don't get the issue. 

Also in pm2 list you'll have a value at instant "t", try the `pm2 monit` command and check values there.

**Comment by papakai** [comment]
I can confirm that I monitored matching processes.
Honestly after we have fixed the cpu load issue on our side I have no longer the possibility to check things with `pm2 monit`.

**Comment by papakai** [comment]
@vmarchaud fyi
