### ISSUE TITLE
Time and Start not working on Darwin

### ISSUE THREAD

**Issue by simonepri** [soyuka/pidusage#47]
![image](https://user-images.githubusercontent.com/3505087/37430250-e00dc488-27d1-11e8-8c8a-8ee7269b7340.png)

**Comment by soyuka** [comment]
Oh nice thanks for that. I think that `lstart` would give a usable output. About `time` I need to parse it and render it as seconds. Thanks for the bug report!

**Comment by soyuka** [comment]
I've fixed this in #45.

**Comment by simonepri** [comment]
Great! Thank you! 🎊

**Comment by simonepri** [comment]
> start is too broad
What do you mean?

**Comment by soyuka** [comment]
I didn't saw that they gave the day in `start`, I read the man and things got clearer. False alert.
