### ISSUE TITLE
Inaccurate CPU usage on multi-threaded processes

### ISSUE THREAD

**Issue by kittyhacker101** [soyuka/pidusage#58]
When a multi-threaded process is putting a low load on many cores, this library will show the CPU usage as 100%.

**Comment by soyuka** [comment]
ping @simonepri

**Comment by simonepri** [comment]
Can you better describe what you mean by "heavily multi-threaded"?

Please provide:
1) Your OS
2) Your CPU
2) Your node version
3) If you can, a screen of the real resource utilization vs the one reported by pidusage.
Thank You!

PS: Note that the percentage provided by pidusage is cumulative.
This means that if you have 100 cores and each of them has a load of 1%, pidusage will report 100% of CPU utilization out of 10000%

**Comment by kittyhacker101** [comment]
OS : Linux 4.16.12-1-ARCH
CPU : Ryzen 7 1800x
NodeJS Version : v10.3.0

The screenshot is attached below.
![image](https://user-images.githubusercontent.com/10361870/40880635-6f58829c-6669-11e8-9e1b-6bac316a7823.png)

**Comment by simonepri** [comment]
Can you please also provide the output of:
```bash
ps -o etime,pid,ppid,pcpu,rss,time
```
Thank you!

**Comment by kittyhacker101** [comment]
I ran that command with the PID of the process supplied as an argument, and this is the output : 
```
ELAPSED   PID  PPID %CPU   RSS     TIME
     01:03 19918 19854  230 39956 00:02:25
```

**Comment by simonepri** [comment]
Does the formula `16*100 / 240 = 6.6 %` returns the CPU percentage that you would expect to see?

**Comment by soyuka** [comment]
@simonepri I guess that the formula there is indeed correct! Do you think that we should patch the library to take this into consideration? Thing is, sometimes you're monitoring a single-threated process (ie javascript thread) therefore it should not use the above formula, correct?

**Comment by simonepri** [comment]
I believe that we need this https://github.com/soyuka/pidusage/issues/57
And then we can return something like that:
```js
{
  cpu: (threads * 100 / pcpu) * 100, // Percentage (0 - 100)
  threads: 5,                        // Number of threads of the process
  memory: 357306368,                 // bytes
  ppid: 312,                         // PPID
  pid: 727,                          // PID
  ctime: 867000,                     // ms user + system time
  elapsed: 6650000,                  // ms since the start of the process
  timestamp: 864000000               // ms since epoch
}
```

**Comment by simonepri** [comment]
@soyuka 
Can you better explain the following?

> Thing is, sometimes you're monitoring a single-threated process (ie javascript thread) therefore it should not use the above formula, or results won't reflect the reality...

**Comment by kittyhacker101** [comment]
I modified the code in the library, replacing the existing CPU usage formula with the one you specified above, and now it does this (process was using 0% CPU in the system's task manager).
![image](https://user-images.githubusercontent.com/10361870/40889308-3715db5e-6719-11e8-9c23-5873b59f9f83.png)

**Comment by kittyhacker101** [comment]
So, I wrote my own snippet to detect CPU usage (` cpu / (os.cpus().length * 100) * 100`), and it shows a value much closer to what the system task manager says.

**Comment by simonepri** [comment]
Yes sorry, I reversed the nominator and denominator of the fraction.
We will work on this as soon as possible.

**Comment by kittyhacker101** [comment]
Oh, okay.

**Comment by soyuka** [comment]
> Can you better explain the following?

It's silly after a second though. 
It'd be great to have the thread count as an additional information indeed.. Maybe we could partially support them on OSes that work? Anyway thanks for the report @kittyhacker101 !

**Comment by simonepri** [comment]
@kittyhacker101 can you confirm that the bug is solved?

**Comment by kittyhacker101** [comment]
The bug in question is solved, but due to this library's averaging of the CPU usage, it takes a while for it to show the correct value (making it a lot less useful).

**Comment by simonepri** [comment]
Can you better explain what "a while" means? It should be really fast on linux.

**Comment by kittyhacker101** [comment]
By "a while", I mean it could take 2+ minutes, to adjust to the correct CPU usage.

**Comment by simonepri** [comment]
That's weird.
It should be as fast as your activity monitor.
Under the hood it uses `ps` so it should be fast and "accurate".
Could you see if the values given by ps matches with the one given by pidtree?

Thank You for the help!

**Comment by lengband** [comment]
> 

hi, i hava a querstion.
Why is it in version 2.0.7 and not in version 2.0.8?

**Comment by lengband** [comment]
hi, i hava a querstion about cpu in lib/ps.js.
Why is it like this `var cpu = parseFloat(line[3].replace(',', '.'), 10) / os.cpus().length` in version 2.0.7, but find code `var cpu = parseFloat(line[3].replace(',', '.'), 10)` in version 2.0.8
