### ISSUE TITLE
ps is computing load starting with process start time whereas procfile is computing load since last call

### ISSUE THREAD

**Issue by soyuka** [soyuka/pidusage#64]
https://unix.stackexchange.com/questions/58539/top-and-ps-not-showing-the-same-cpu-result 

In a monitoring situation, `procfile` would be more precise and `ps` would give an overview.

**Comment by simonepri** [comment]
I believe that the correct behaviour should be `computing load since last call`.
Isn't it?

We can use `ps` to do the same computation we do for `procfile` and `wmic` (just using etime and stime instead of using pcpu)
The maths for the 3 method should be almost the identical.

**Comment by vmarchaud** [comment]
indeed however i personally prefer to use a fs read instead of spawning a process to get this metric.

**Comment by soyuka** [comment]
> We can use ps to do the same computation we do for procfile and wmic (just using etime and stime instead of using pcpu)

Yes but then we need to introduce history on ps calls to get elapsed time since last call.,
